spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: 09139349
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    com.tutorial: debug

# waveofmymind-jeonsangjoon-spring-boot-jwtpractice-waveofmymind-jeonsangjoon-spring-boot-jwtpractice
jwt:
  secret: d2F2ZW9mbXltaW5kLWplb25zYW5nam9vbi1zcHJpbmctYm9vdC1qd3RwcmFjdGljZS13YXZlb2ZteW1pbmQtamVvbnNhbmdqb29uLXNwcmluZy1ib290LWp3dHByYWN0aWNl